server:
  port: 9001
spring:
  application:
    name: alibaba-cloud-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8848
  datasource:
    url: jdbc:mysql://localhost:3306/alibaba?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#打开全部监控端点
maagement:
  endpoints:
    web:
      exposure:
        include: '*'