server:
  port: 9002

spring:
  application:
    name: alibaba-cloud-client
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
server-url:
  nacos-user-service: http://alibaba-cloud-server