server:
  port: 9003
spring:
  application:
    name: alibaba-cloud-server
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: localhost:8848
#    sentinel:
#      transport:
#        #配置Sentinel Dashboard地址
#        dashboard: localhost:8080
#        #默认8719端口，假如被占用会自动从8719开始一依次+1扫描，知道找到未占用的端口
#        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
